# Generated by Django 4.2.7 on 2023-11-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='collection_point',
        ),
        migrations.DeleteModel(
            name='CollectionPoint',
        ),
    ]
