# Generated by Django 4.2.7 on 2023-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_adminallocation_clientrequest_collectorreport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
