# Generated by Django 4.2.7 on 2023-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='type_of_waste',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Glass', 'Glass')], max_length=50),
        ),
    ]
