# Generated by Django 4.2.7 on 2023-12-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectorreport',
            name='allocation',
        ),
        migrations.DeleteModel(
            name='AdminAllocation',
        ),
    ]
