# Generated by Django 4.2.7 on 2023-12-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_collectorreport_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
    ]
