# Generated by Django 4.2.7 on 2023-12-20 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_collector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectorreport',
            old_name='timestamp',
            new_name='report_timestamp',
        ),
        migrations.RemoveField(
            model_name='collectorreport',
            name='amount_of_waste',
        ),
        migrations.RemoveField(
            model_name='collectorreport',
            name='report_details',
        ),
        migrations.AddField(
            model_name='collectorreport',
            name='client_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.clientrequest'),
        ),
        migrations.AddField(
            model_name='collectorreport',
            name='collector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectorreport',
            name='detail',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='collectorreport',
            name='material',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='collectorreport',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.clientrequest')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
