# Generated by Django 4.2.7 on 2023-12-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_timestamp_collectorreport_report_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='allocation_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='collectorreport',
            old_name='report_timestamp',
            new_name='timestamp',
        ),
    ]
