# Generated by Django 4.2.7 on 2023-12-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_allocation_timestamp_allocation_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorreport',
            name='confirmation_from_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectorreport',
            name='finalprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectorreport',
            name='transaction_completed',
            field=models.BooleanField(default=False),
        ),
    ]
