# Generated by Django 4.2.7 on 2023-12-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_collectorreport_confirmation_from_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorreport',
            name='client_request',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.clientrequest'),
        ),
    ]
