# Generated by Django 4.2.7 on 2023-12-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_clientrequest_type_of_waste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='type_of_waste',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Glass', 'Glass'), ('Metal', 'Metal'), ('Wet waste', 'Wet waste'), ('Dry waste', 'Dry waste'), ('Others', 'Others')], max_length=50),
        ),
    ]
